#!/bin/sh

venv/bin/python main.py --dataset_config configs/refcoco.json --batch_size 4 --load refcoco_EB3_checkpoint.pth --ema --text_encoder_lr 1e-5 --lr 5e-5 --backbone "timm_tf_efficientnet_b3_ns" --epochs=10 --output-dir output
