#!/bin/sh

venv/bin/python main.py --dataset_config configs/refcoco.json --batch_size 4 --load https://zenodo.org/record/4721981/files/pretrained_resnet101_checkpoint.pth?download=1 --ema --text_encoder_lr 1e-5 --lr 5e-5
